extern "C" int __stdcall csSoftwareReset(int Device);
extern "C" int __stdcall csGetVersion();
extern "C" int __stdcall csGetVersionEx(char* sPath);
extern "C" int __stdcall hisGetBasicData(char *pBuffer,short *iBufferLen);
extern "C" int __stdcall hisGetRegisterBasic(char *pBuffer,short *iBufferLen);
extern "C" int __stdcall hisGetRegisterPrevent(char *pBuffer,short *iBufferLen);
extern "C" int __stdcall hisGetRegisterPregnant(char *pBuffer,short *iBufferLen);
extern "C" int __stdcall hisGetTreatmentNoNeedHPC(char *pBuffer,short *iBufferLen);
extern "C" int __stdcall hisGetCumulativeData(char *pBuffer,short *iBufferLen);
extern "C" int __stdcall hisGetCumulativeFee(char *pBuffer,short *iBufferLen);
extern "C" int __stdcall hisGetTreatmentNeedHPC(char *pBuffer,short *iBufferLen);
extern "C" int __stdcall hisGetSeqNumber(char *cTreatItem,char *cBabyTreat,char *pBuffer,short *iBufferLen);
extern "C" int __stdcall hisReadPrescription(char *pOutpatientPrescription,short *iBufferLenOutpatient,char *pLongTermPrescription,short *iBufferLenLongTerm,char *pImportantTreatmentCode,short *iBufferLenImportant,char *pIrritationDrug,short *iBufferLenIrritation);
extern "C" int __stdcall hisGetInoculateData(char *pBuffer,short *iBufferLen);
extern "C" int __stdcall hisGetOrganDonate(char *pBuffer,short *iBufferLen);
extern "C" int __stdcall hisGetEmergentTel(char *pBuffer,short *iBufferLen);
extern "C" int __stdcall hisGetLastSeqNum(char *pBuffer,short *iBufferLen);
extern "C" int __stdcall hisGetCardStatus(short CardType);
extern "C" int __stdcall hisWriteTreatmentCode(char *pDateTime,char *pPatientID,char *pPatientBirthDate,char *pDataWrite,char *pBufferDocID);
extern "C" int __stdcall hisWriteTreatmentFee(char *pDateTime,char *pPatientID,char *pPatientBirthDate,char *pDataWrite);
extern "C" int __stdcall hisWritePrescription(char *pDateTime,char *pPatientID,char *pPatientBirthDate,char *pDataWrite);
extern "C" int __stdcall hisWriteNewBorn(char *pPatientID,char *pPatientBirthDate,char *pNewBornDate,char *pNoOfDelivered);
extern "C" int __stdcall hisWriteAllergicMedicines(char *pPatientID,char *pPatientBirthDate,char *pDataWrite,char *pBufferDocID);
extern "C" int __stdcall hisWriteOrganDonate(char *pPatientID,char *pPatientBirthDate,char *pOrganDonate);
extern "C" int __stdcall hisWriteHealthInsurance(char *pPatientID,char *pPatientBirthDate,char *pServiceItem,char *pServiceItemCode);
extern "C" int __stdcall hisWriteEmergentTel(char *pPatientID,char *pPatientBirthDate,char *pEmergentTel);
extern "C" int __stdcall hisWritePredeliveryCheckup(char *pPatientID,char *pPatientBirthDate,char *pCheckupCode);
extern "C" int __stdcall hisDeletePredeliveryData(char *pPatientID,char *pPatientBirthDate);
extern "C" int __stdcall hisWriteInoculateData(char *pPatientID,char *pPatientBirthDate,char *pItem,char * pPackageNumber);
extern "C" int __stdcall csVerifyHCPIN();
extern "C" int __stdcall csInputHCPIN();
extern "C" int __stdcall csDisableHCPIN();
extern "C" int __stdcall csUpdateHCContents();
extern "C" int __stdcall csOpenCom(int pComNum);
extern "C" int __stdcall csCloseCom();
extern "C" int __stdcall hisGetCriticalIllness(char *pBuffer,short *iBufferLen);
extern "C" int __stdcall hisGetCriticalIllnessID(char* pPatientID,char* pPatientBirthDate,char *pBuffer,short *iBufferLen);
extern "C" int __stdcall csGetDateTime(char *pBuffer,short *iBufferLen);
extern "C" int __stdcall csGetCardNo(short CardType,char *pBuffer,short *iBufferLen);
extern "C" int __stdcall csISSetPIN();
extern "C" int __stdcall hisGetSeqNumber256(char *cTreatItem,char *cBabyTreat,char *cTreatAfterCheck,char *pBuffer,short *iBufferLen);
extern "C" int __stdcall hisGetRegisterBasic2(char *pBuffer ,short *iBufferLen);
extern "C" int __stdcall csUnGetSeqNumber(char *pUnTreatDate);
extern "C" int __stdcall csGetLastUnTreatmentData(char *pBuffer,short *iBufferLen);
extern "C" int __stdcall csUpdateHCNoReset();
extern "C" int __stdcall hisGetInsurerData(char *pBuffer,short *iBufferLen);
extern "C" int __stdcall csVerifySAMDC();
extern "C" int __stdcall csUploadData(char *pUploadFileName,char *fFileSize,char *pNumber,char *pBuffer,short *iBufferLen);
extern "C" int __stdcall hpcGetHPCStatus(int Req,short *Status);
extern "C" int __stdcall hpcVerifyHPCPIN();
extern "C" int __stdcall hpcInputHPCPIN();
extern "C" int __stdcall hpcUnlockHPC();
extern "C" int __stdcall hpcGetHPCSN(char *pBuffer,short *iBufferLen);
extern "C" int __stdcall hpcGetHPCSSN(char *pBuffer,short *iBufferLen);
extern "C" int __stdcall hpcGetHPCCNAME(char *pBuffer,short *iBufferLen);
extern "C" int __stdcall hpcGetHPCENAME(char *pBuffer,short *iBufferLen);
extern "C" int __stdcall hisReadPrescriptMain(char *pOutpatientPrescription,short *iBufferLenOutpatient,short iStartPos,short iEndPos,short *iRecCount);
extern "C" int __stdcall hisReadPrescriptLongTerm(char *pLongTermPrescription,short *iBufferLenLongTerm,short iStartPos,short iEndPos,short *iRecCount);
extern "C" int __stdcall hisReadPrescriptHVE(char *pImportantTreatmentCode,short *iBufferLenImportant,short iStartPos,short iEndPos,short *iRecCount);
extern "C" int __stdcall hisReadPrescriptAllergic(char *pIrritationDrug,short *iBufferLenIrritation,short iStartPos,short iEndPos,short *iRecCount);
extern "C" int __stdcall hisWriteMultiPrescript(char *pDateTime,char *pPatientID,char *pPatientBirthDate,char *pDataWrite,short *iWriteCount);
extern "C" int __stdcall hisWriteMultiPrescriptSign(char *pDateTime,char *pPatientID,char *pPatientBirthDate,char *pDataWrite,short *iWriteCount,char *pBuffer,short* iLen);
extern "C" int __stdcall hisWriteAllergicNum(char *pPatientID,char *pPatientBirthDate,char *pDataWrite,char *pBufferDocID,short iNum);
extern "C" int __stdcall hisWriteTreatmentData(char *pDateTime,char *pPatientID,char *pPatientBirthDate,char *pDataWrite,char *pBufferDocID);
extern "C" int __stdcall hisWritePrescriptionSign(char *pDateTime,char *pPatientID,char *pPatientBirthDate,char *pDataWrite,char *pBuffer,short* iLen);
extern "C" int __stdcall csGetHospID(char *pBuffer,short *iBufferLen);
extern "C" int __stdcall HCA_GNFuncCall(long  nFuncID,char* InBuf,char* OutBuf,long P1,long P2,long P3,long P4,long P5);
