# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/cytu/usr/src/py/mycis/designer/dlg_tk_abn.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dlg_tk_abn(object):
    def setupUi(self, dlg_tk_abn):
        dlg_tk_abn.setObjectName(_fromUtf8("dlg_tk_abn"))
        dlg_tk_abn.resize(350, 246)
        dlg_tk_abn.setMinimumSize(QtCore.QSize(350, 246))
        dlg_tk_abn.setMaximumSize(QtCore.QSize(350, 247))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        dlg_tk_abn.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/img/receptionist.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dlg_tk_abn.setWindowIcon(icon)
        dlg_tk_abn.setStyleSheet(_fromUtf8("font: 75 12pt \"Microsoft JhengHei\";"))
        self.formLayout = QtGui.QFormLayout(dlg_tk_abn)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(dlg_tk_abn)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.led_name = QtGui.QLineEdit(dlg_tk_abn)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.led_name.setFont(font)
        self.led_name.setObjectName(_fromUtf8("led_name"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.led_name)
        self.label_2 = QtGui.QLabel(dlg_tk_abn)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.led_pid = QtGui.QLineEdit(dlg_tk_abn)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.led_pid.setFont(font)
        self.led_pid.setObjectName(_fromUtf8("led_pid"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.led_pid)
        self.label_3 = QtGui.QLabel(dlg_tk_abn)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.ded_birth = QtGui.QDateEdit(dlg_tk_abn)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.ded_birth.setFont(font)
        self.ded_birth.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.ded_birth.setMinimumDate(QtCore.QDate(1752, 10, 14))
        self.ded_birth.setCalendarPopup(True)
        self.ded_birth.setObjectName(_fromUtf8("ded_birth"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.ded_birth)
        self.cbo_abn = QtGui.QComboBox(dlg_tk_abn)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.cbo_abn.setFont(font)
        self.cbo_abn.setObjectName(_fromUtf8("cbo_abn"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.cbo_abn)
        self.bnb = QtGui.QDialogButtonBox(dlg_tk_abn)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.bnb.setFont(font)
        self.bnb.setStyleSheet(_fromUtf8(""))
        self.bnb.setOrientation(QtCore.Qt.Horizontal)
        self.bnb.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.bnb.setObjectName(_fromUtf8("bnb"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.bnb)
        self.label_6 = QtGui.QLabel(dlg_tk_abn)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_6)
        self.dted_tk = QtGui.QDateTimeEdit(dlg_tk_abn)
        self.dted_tk.setCalendarPopup(True)
        self.dted_tk.setObjectName(_fromUtf8("dted_tk"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.dted_tk)
        self.label_5 = QtGui.QLabel(dlg_tk_abn)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.cbo_state = QtGui.QComboBox(dlg_tk_abn)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.cbo_state.setFont(font)
        self.cbo_state.setObjectName(_fromUtf8("cbo_state"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.cbo_state)
        self.label_4 = QtGui.QLabel(dlg_tk_abn)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label.setBuddy(self.led_name)
        self.label_2.setBuddy(self.led_pid)
        self.label_3.setBuddy(self.ded_birth)
        self.label_6.setBuddy(self.ded_birth)
        self.label_5.setBuddy(self.cbo_state)
        self.label_4.setBuddy(self.cbo_abn)

        self.retranslateUi(dlg_tk_abn)
        QtCore.QObject.connect(self.bnb, QtCore.SIGNAL(_fromUtf8("accepted()")), dlg_tk_abn.accept)
        QtCore.QObject.connect(self.bnb, QtCore.SIGNAL(_fromUtf8("rejected()")), dlg_tk_abn.reject)
        QtCore.QMetaObject.connectSlotsByName(dlg_tk_abn)

    def retranslateUi(self, dlg_tk_abn):
        dlg_tk_abn.setWindowTitle(_translate("dlg_tk_abn", "異常掛號：請輸入患者資料", None))
        self.label.setText(_translate("dlg_tk_abn", "患者姓名", None))
        self.label_2.setText(_translate("dlg_tk_abn", "身份證號", None))
        self.label_3.setText(_translate("dlg_tk_abn", "出生日期", None))
        self.label_6.setText(_translate("dlg_tk_abn", "掛號時間", None))
        self.label_5.setText(_translate("dlg_tk_abn", "身份註記", None))
        self.label_4.setText(_translate("dlg_tk_abn", "異常狀態", None))

import mycis_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    dlg_tk_abn = QtGui.QDialog()
    ui = Ui_dlg_tk_abn()
    ui.setupUi(dlg_tk_abn)
    dlg_tk_abn.show()
    sys.exit(app.exec_())

