# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/cytu/usr/src/py/mycis/designer/dlg_tk_ini.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dlg_tk_ini(object):
    def setupUi(self, dlg_tk_ini):
        dlg_tk_ini.setObjectName(_fromUtf8("dlg_tk_ini"))
        dlg_tk_ini.resize(433, 171)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        dlg_tk_ini.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/img/receptionist.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dlg_tk_ini.setWindowIcon(icon)
        dlg_tk_ini.setStyleSheet(_fromUtf8("font: 75 12pt \"Microsoft JhengHei\";"))
        self.gridLayout_2 = QtGui.QGridLayout(dlg_tk_ini)
        self.gridLayout_2.setMargin(5)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setMargin(5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(dlg_tk_ini)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setMargin(5)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.rbn_gen = QtGui.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.rbn_gen.setFont(font)
        self.rbn_gen.setChecked(True)
        self.rbn_gen.setObjectName(_fromUtf8("rbn_gen"))
        self.horizontalLayout.addWidget(self.rbn_gen)
        self.rbn_amend = QtGui.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.rbn_amend.setFont(font)
        self.rbn_amend.setObjectName(_fromUtf8("rbn_amend"))
        self.horizontalLayout.addWidget(self.rbn_amend)
        self.rbn_debt = QtGui.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.rbn_debt.setFont(font)
        self.rbn_debt.setObjectName(_fromUtf8("rbn_debt"))
        self.horizontalLayout.addWidget(self.rbn_debt)
        self.rbn_voc = QtGui.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.rbn_voc.setFont(font)
        self.rbn_voc.setObjectName(_fromUtf8("rbn_voc"))
        self.horizontalLayout.addWidget(self.rbn_voc)
        self.rbn_amend_f = QtGui.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.rbn_amend_f.setFont(font)
        self.rbn_amend_f.setObjectName(_fromUtf8("rbn_amend_f"))
        self.horizontalLayout.addWidget(self.rbn_amend_f)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setMargin(5)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.chk_same = QtGui.QCheckBox(dlg_tk_ini)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.chk_same.setFont(font)
        self.chk_same.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chk_same.setChecked(False)
        self.chk_same.setObjectName(_fromUtf8("chk_same"))
        self.gridLayout.addWidget(self.chk_same, 0, 1, 1, 1)
        self.chk_critical = QtGui.QCheckBox(dlg_tk_ini)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.chk_critical.setFont(font)
        self.chk_critical.setObjectName(_fromUtf8("chk_critical"))
        self.gridLayout.addWidget(self.chk_critical, 0, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtGui.QDialogButtonBox(dlg_tk_ini)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.buttonBox.setFont(font)
        self.buttonBox.setStyleSheet(_fromUtf8(""))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(dlg_tk_ini)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), dlg_tk_ini.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), dlg_tk_ini.reject)
        QtCore.QMetaObject.connectSlotsByName(dlg_tk_ini)
        dlg_tk_ini.setTabOrder(self.rbn_gen, self.rbn_amend)
        dlg_tk_ini.setTabOrder(self.rbn_amend, self.rbn_debt)
        dlg_tk_ini.setTabOrder(self.rbn_debt, self.chk_same)
        dlg_tk_ini.setTabOrder(self.chk_same, self.chk_critical)
        dlg_tk_ini.setTabOrder(self.chk_critical, self.buttonBox)

    def retranslateUi(self, dlg_tk_ini):
        dlg_tk_ini.setWindowTitle(_translate("dlg_tk_ini", "掛號", None))
        self.groupBox.setTitle(_translate("dlg_tk_ini", "掛號類型", None))
        self.rbn_gen.setText(_translate("dlg_tk_ini", "一般", None))
        self.rbn_amend.setText(_translate("dlg_tk_ini", "補卡", None))
        self.rbn_debt.setText(_translate("dlg_tk_ini", "欠卡", None))
        self.rbn_voc.setText(_translate("dlg_tk_ini", "職災", None))
        self.rbn_amend_f.setText(_translate("dlg_tk_ini", "快速補卡", None))
        self.chk_same.setText(_translate("dlg_tk_ini", "同一療程", None))
        self.chk_critical.setText(_translate("dlg_tk_ini", "重大傷病", None))

import mycis_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    dlg_tk_ini = QtGui.QDialog()
    ui = Ui_dlg_tk_ini()
    ui.setupUi(dlg_tk_ini)
    dlg_tk_ini.show()
    sys.exit(app.exec_())

