# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/cytu/usr/src/py/mycis/designer/win_main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_win_main(object):
    def setupUi(self, win_main):
        win_main.setObjectName(_fromUtf8("win_main"))
        win_main.setEnabled(True)
        win_main.resize(951, 591)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        win_main.setFont(font)
        win_main.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/img/mycis.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        win_main.setWindowIcon(icon)
        win_main.setStyleSheet(_fromUtf8("font: 75 12pt \"Microsoft JhengHei\";"))
        self.centralwidget = QtGui.QWidget(win_main)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        win_main.setCentralWidget(self.centralwidget)
        self.mnb = QtGui.QMenuBar(win_main)
        self.mnb.setGeometry(QtCore.QRect(0, 0, 951, 33))
        self.mnb.setObjectName(_fromUtf8("mnb"))
        self.menu = QtGui.QMenu(self.mnb)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtGui.QMenu(self.mnb)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        self.menu_3 = QtGui.QMenu(self.mnb)
        self.menu_3.setObjectName(_fromUtf8("menu_3"))
        self.menu_V = QtGui.QMenu(self.mnb)
        self.menu_V.setObjectName(_fromUtf8("menu_V"))
        win_main.setMenuBar(self.mnb)
        self.tb = QtGui.QToolBar(win_main)
        self.tb.setIconSize(QtCore.QSize(48, 48))
        self.tb.setObjectName(_fromUtf8("tb"))
        win_main.addToolBar(QtCore.Qt.TopToolBarArea, self.tb)
        self.stb = QtGui.QStatusBar(win_main)
        self.stb.setObjectName(_fromUtf8("stb"))
        win_main.setStatusBar(self.stb)
        self.act_tk = QtGui.QAction(win_main)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/img/receptionist.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_tk.setIcon(icon1)
        self.act_tk.setObjectName(_fromUtf8("act_tk"))
        self.act_quit = QtGui.QAction(win_main)
        self.act_quit.setObjectName(_fromUtf8("act_quit"))
        self.act_stat = QtGui.QAction(win_main)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/img/chart.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_stat.setIcon(icon2)
        self.act_stat.setObjectName(_fromUtf8("act_stat"))
        self.act_renew = QtGui.QAction(win_main)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/img/system_software_update.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_renew.setIcon(icon3)
        self.act_renew.setObjectName(_fromUtf8("act_renew"))
        self.act_app = QtGui.QAction(win_main)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/img/db_comit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_app.setIcon(icon4)
        self.act_app.setObjectName(_fromUtf8("act_app"))
        self.act_backup = QtGui.QAction(win_main)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/img/database.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_backup.setIcon(icon5)
        self.act_backup.setObjectName(_fromUtf8("act_backup"))
        self.act_about = QtGui.QAction(win_main)
        self.act_about.setIcon(icon)
        self.act_about.setObjectName(_fromUtf8("act_about"))
        self.act_inst = QtGui.QAction(win_main)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/img/document-open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_inst.setIcon(icon6)
        self.act_inst.setObjectName(_fromUtf8("act_inst"))
        self.act_patient = QtGui.QAction(win_main)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/img/patient.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_patient.setIcon(icon7)
        self.act_patient.setObjectName(_fromUtf8("act_patient"))
        self.menu.addAction(self.act_backup)
        self.menu.addAction(self.act_renew)
        self.menu.addSeparator()
        self.menu.addAction(self.act_quit)
        self.menu.addSeparator()
        self.menu_2.addAction(self.act_tk)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.act_app)
        self.menu_2.addSeparator()
        self.menu_3.addAction(self.act_about)
        self.menu_V.addAction(self.act_stat)
        self.menu_V.addAction(self.act_inst)
        self.menu_V.addAction(self.act_patient)
        self.mnb.addAction(self.menu.menuAction())
        self.mnb.addAction(self.menu_2.menuAction())
        self.mnb.addAction(self.menu_V.menuAction())
        self.mnb.addAction(self.menu_3.menuAction())
        self.tb.addAction(self.act_tk)
        self.tb.addSeparator()
        self.tb.addAction(self.act_stat)
        self.tb.addAction(self.act_inst)
        self.tb.addAction(self.act_patient)
        self.tb.addSeparator()

        self.retranslateUi(win_main)
        QtCore.QMetaObject.connectSlotsByName(win_main)

    def retranslateUi(self, win_main):
        win_main.setWindowTitle(_translate("win_main", "mycis", None))
        self.menu.setTitle(_translate("win_main", "系統(&M)", None))
        self.menu_2.setTitle(_translate("win_main", "工作(&W)", None))
        self.menu_3.setTitle(_translate("win_main", "說明(&H)", None))
        self.menu_V.setTitle(_translate("win_main", "查詢(&S)", None))
        self.tb.setWindowTitle(_translate("win_main", "toolBar", None))
        self.act_tk.setText(_translate("win_main", "掛號(&R)", None))
        self.act_tk.setIconText(_translate("win_main", "掛號", None))
        self.act_tk.setToolTip(_translate("win_main", "掛號", None))
        self.act_tk.setShortcut(_translate("win_main", "Alt+R", None))
        self.act_quit.setText(_translate("win_main", "離開(&Q)", None))
        self.act_quit.setToolTip(_translate("win_main", "離開", None))
        self.act_quit.setShortcut(_translate("win_main", "Alt+Q", None))
        self.act_stat.setText(_translate("win_main", "點數(&T)", None))
        self.act_stat.setIconText(_translate("win_main", "點數", None))
        self.act_stat.setToolTip(_translate("win_main", "點數", None))
        self.act_stat.setShortcut(_translate("win_main", "Alt+T", None))
        self.act_renew.setText(_translate("win_main", "更新(&N)", None))
        self.act_renew.setToolTip(_translate("win_main", "更新", None))
        self.act_renew.setShortcut(_translate("win_main", "Alt+N", None))
        self.act_app.setText(_translate("win_main", "申報(&A)", None))
        self.act_app.setIconText(_translate("win_main", "申報", None))
        self.act_app.setToolTip(_translate("win_main", "申報", None))
        self.act_app.setShortcut(_translate("win_main", "Alt+A", None))
        self.act_backup.setText(_translate("win_main", "備份(&B)", None))
        self.act_backup.setIconText(_translate("win_main", "資料庫備份", None))
        self.act_backup.setToolTip(_translate("win_main", "資料庫備份", None))
        self.act_backup.setShortcut(_translate("win_main", "Alt+B", None))
        self.act_about.setText(_translate("win_main", "關於 mycis ", None))
        self.act_inst.setText(_translate("win_main", "案件(&C)", None))
        self.act_inst.setToolTip(_translate("win_main", "案件", None))
        self.act_inst.setShortcut(_translate("win_main", "Alt+C", None))
        self.act_patient.setText(_translate("win_main", "患者(&P)", None))
        self.act_patient.setToolTip(_translate("win_main", "患者", None))
        self.act_patient.setShortcut(_translate("win_main", "Alt+P", None))

import mycis_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    win_main = QtGui.QMainWindow()
    ui = Ui_win_main()
    ui.setupUi(win_main)
    win_main.show()
    sys.exit(app.exec_())

